<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>11</LangVersion>
    <NoWarn>MSB3277,IDE0011,IDE0005,IDE0001,IDE0002,IDE0003,IDE0007,IDE0009,CA1707,CA1711,CA1051,CA1812,CA1815,CA1819,CA1825,CA1834,CA1838,CA2211,CA2227,CA1031,CS1591,RUST005,RUST003,RA0013,RA0030,RA0040,RA0050,IDE0028</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>disable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <DefaultItemExcludes>$(DefaultItemExcludes);build\**;RustServerManager\**;RustPluginUploader\**;CursorReset\**;PostMaster\**;rust-gradient-generator\**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == ''">
    <Configuration>Oxide</Configuration>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Oxide'">
    <DefineConstants>OXIDE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Carbon'">
    <DefineConstants>CARBON</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="RustVersion" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>Managed\UnityEngine.AIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>Managed\Facepunch.Console.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>Managed\Facepunch.UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>Managed\Facepunch.System.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>Managed\Facepunch.Network.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>Managed\Rust.Data.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rust.Clans">
      <HintPath>Managed\Rust.Clans.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rust.Global">
      <HintPath>Managed\Rust.Global.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rust.Localization">
      <HintPath>Managed\Rust.Localization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>Managed\Oxide\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Oxide.Core">
      <HintPath>Managed\Oxide\Oxide.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Oxide.Rust">
      <HintPath>Managed\Oxide\Oxide.Rust.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Oxide.Common">
      <HintPath>Managed\Oxide\Oxide.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Oxide.CSharp">
      <HintPath>Managed\Oxide\Oxide.CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Oxide.References">
      <HintPath>Managed\Oxide\Oxide.References.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="rust-analyzer" Version="8.0.36" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.13.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="./.rust-analyzer/*.json" />
  </ItemGroup>
</Project>
