import re

file_path = r"d:\Fix\rust-template-main\rust-template\plugins\Skill Tree 1.7.11\SkillTree.cs"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

translations = {
    '"None"] = "This has no buffs."': '"None"] = "Немає бафів."',
    '"Mining_Yield"] = "This skill increases your mining yield by <color=#42f105>{0}%</color> per level."': '"Mining_Yield"] = "Ця навичка збільшує ваш видобуток руди на <color=#42f105>{0}%</color> за рівень."',
    '"Instant_Mine"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to instantly mine out a node on hit."': '"Instant_Mine"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень миттєво добути всю руду з вузла при ударі."',
    '"Smelt_On_Mine"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to refine the mined ore."': '"Smelt_On_Mine"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень переплавити добуту руду."',
    '"Mining_Luck"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to receive a random item when you mine out a node."': '"Mining_Luck"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати випадковий предмет під час добування руди."',
    '"Skinning_Luck"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to receive a random item when you skin out a corpse."': '"Skinning_Luck"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати випадковий предмет під час білування трупа."',
    '"Harvesting_Luck"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to receive a random item when you collect items."': '"Harvesting_Luck"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати випадковий предмет під час збору."',
    '"Fishing_Luck"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to receive a random item when you catch a fish."': '"Fishing_Luck"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати випадковий предмет під час риболовлі."',
    '"Metal_Detector_Luck"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to receive a random item when you dig up a cache that has been found using a metal detector."': '"Metal_Detector_Luck"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати випадковий предмет при викопуванні схованки з металошукачем."',
    '"Mining_Tool_Durability"] = "This skill decreases the durability loss of your mining equipment by <color=#42f105>{0}%</color> per level."': '"Mining_Tool_Durability"] = "Ця навичка зменшує втрату міцності вашого інструменту для добування руди на <color=#42f105>{0}%</color> за рівень."',
    '"Mining_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill allows you to locate nodes within a <color=#42f105>{0}m</color> radius."': '"Mining_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка дозволяє знаходити вузли руди в радіусі <color=#42f105>{0}м</color>."',
    '"Medical_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill gives you a <color=#42f105>{0}%</color> chance to resurrect at your last place of death."': '"Medical_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка дає вам <color=#42f105>{0}%</color> шансу воскреснути на місці вашої смерті."',
    '"Harvester_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill gives you the ability to set the genetic composition for plants you deploy{0}."': '"Harvester_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка дає вам можливість встановлювати генетичний склад рослин, які ви саджаєте{0}."',
    '"Woodcutting_Yield"] = "This skill increases your woodcutting yield by <color=#42f105>{0}%</color> per level."': '"Woodcutting_Yield"] = "Ця навичка збільшує ваш видобуток дерева на <color=#42f105>{0}%</color> за рівень."',
    '"Instant_Chop"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to instantly chop a tree down on hit."': '"Instant_Chop"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень миттєво зрубати дерево при ударі."',
    '"Regrowth"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to respawn a chopped tree."': '"Regrowth"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень миттєво відновити зрубане дерево."',
    '"Woodcutting_Luck"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to receive a random item when you cut down a tree."': '"Woodcutting_Luck"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати випадковий предмет під час рубання дерева."',
    '"Woodcutting_Coal"] = "This skill gives you a <color=#42f105>{0}%</color> chance to receive some charcoal while woodcutting."': '"Woodcutting_Coal"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу отримати вугілля під час рубання дерева."',
    '"Woodcutting_Tool_Durability"] = "This skill decreases the durability loss of your woodcutting equipment by <color=#42f105>{0}%</color> per level."': '"Woodcutting_Tool_Durability"] = "Ця навичка зменшує втрату міцності вашого інструменту для рубання дерева на <color=#42f105>{0}%</color> за рівень."',
    '"Woodcutting_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill will harvest surrounding trees in a <color=#42f105>{0}m</color> radius when you cut a tree down."': '"Woodcutting_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка зрубає навколишні дерева в радіусі <color=#42f105>{0}м</color> при зрубуванні дерева."',
    '"Skinning_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> Killing an animal while this skill is active will give you a temporary buff. <color=#42f105>{0}</color>"': '"Skinning_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Вбивство тварини, коли ця навичка активна, дасть вам тимчасовий баф. <color=#42f105>{0}</color>"',
    '"Combat_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill will heal you for <color=#42f105>{0}%</color> of the damage done to certain enemies. Enemies: {1}"': '"Combat_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка зцілить вас на <color=#42f105>{0}%</color> від завданої шкоди певним ворогам. Вороги: {1}"',
    '"Scavengers_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill automatically recycles components from barrels when broken."': '"Scavengers_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка автоматично перероблює компоненти з бочок при їх знищенні."',
    '"Build_Craft_Ultimate"] = "<color=#db03cb>ULTIMATE:</color> This skill will allow you to use any coloured swipe card in any reader to access it{0}."': '"Build_Craft_Ultimate"] = "<color=#db03cb>УЛЬТИМАТУМ:</color> Ця навичка дозволить вам використовувати картку будь-якого кольору в будь-якому зчитувачі{0}."',
    '"Skinning_Yield"] = "This skill increases your skinning yield by <color=#42f105>{0}%</color> per level."': '"Skinning_Yield"] = "Ця навичка збільшує ваш видобуток при білуванні на <color=#42f105>{0}%</color> за рівень."',
    '"Instant_Skin"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to instantly skin out the animal on hit."': '"Instant_Skin"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень миттєво оббілувати тварину при ударі."',
    '"Skinning_Tool_Durability"] = "This skill decreases the durability loss of your skinning equipment by <color=#42f105>{0}%</color> per level"': '"Skinning_Tool_Durability"] = "Ця навичка зменшує втрату міцності вашого інструменту для білування на <color=#42f105>{0}%</color> за рівень"',
    '"Skin_Cook"] = "This skill gives you a <color=#42f105>{0}%</color> per level chance of receiving your meat cooked, rather than raw, while skinning."': '"Skin_Cook"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати смажене м\'ясо замість сирого при білуванні."',
    '"Permission"] = ""': '"Permission"] = ""',
    '"Harvest_Wild_Yield"] = "This skill increases your harvesting yield by <color=#42f105>{0}%</color> per level while harvesting wild collectibles."': '"Harvest_Wild_Yield"] = "Ця навичка збільшує ваш видобуток на <color=#42f105>{0}%</color> за рівень при зборі диких рослин."',
    '"Harvest_Grown_Yield"] = "This skill increases your harvesting yield by <color=#42f105>{0}%</color> per level while harvesting grown plants."': '"Harvest_Grown_Yield"] = "Ця навичка збільшує ваш видобуток на <color=#42f105>{0}%</color> за рівень при зборі вирощених рослин."',
    '"Extra_Fish"] = "This skill gives you a <color=#42f105>{0}%</color> per level chance of receiving an extra fish when you catch a fish."': '"Extra_Fish"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати додаткову рибу при її лові."',
    '"Double_Bandage_Heal"] = "This skill will double the amount of healing received from bandages."': '"Double_Bandage_Heal"] = "Ця навичка подвоює кількість зцілення, отриманого від бинтів."',
    '"Radiation_Reduction"] = "This skill will reduce radiation damage received by <color=#42f105>{0}%</color> per level."': '"Radiation_Reduction"] = "Ця навичка зменшує отриману шкоду від радіації на <color=#42f105>{0}%</color> за рівень."',
    '"Extra_Food_Water"] = "This skill will increase the amount of calories and hydration received by <color=#42f105>{0}%</color> per level when eating food."': '"Extra_Food_Water"] = "Ця навичка збільшує кількість калорій та гідратації від їжі на <color=#42f105>{0}%</color> за рівень."',
    '"WaterBreathing"] = "This skill will allow you to breath underwater for <color=#42f105>{0} seconds</color> per level."': '"WaterBreathing"] = "Ця навичка дозволяє вам дихати під водою <color=#42f105>{0} секунд</color> за рівень."',
    '"SharkResistance"] = "This skill will reduce the damage received from sharks by <color=#42f105>{0}%</color> per level."': '"SharkResistance"] = "Ця навичка зменшує шкоду від акул на <color=#42f105>{0}%</color> за рівень."',
    '"SharkSkinner"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of finding a useful item when skinning a shark."': '"SharkSkinner"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень знайти корисний предмет при білуванні акули."',
    '"DeepSeaLooter"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of finding a useful item when looting crates underwater."': '"DeepSeaLooter"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень знайти корисний предмет при обшуку ящиків під водою."',
    '"InstantUntie"] = "This skill allows you to instantly untie underwater crates."': '"InstantUntie"] = "Ця навичка дозволяє миттєво відв\'язувати підводні ящики."',
    '"UnderwaterDamageBonus"] = "This skill increases the damage done while you are underwater by <color=#42f105>{0}%</color> per level."': '"UnderwaterDamageBonus"] = "Ця навичка збільшує нанесену вами шкоду під водою на <color=#42f105>{0}%</color> за рівень."',
    '"Fire_Damage_Reduction"] = "This skill will reduce fire damage by <color=#42f105>{0}%</color> per level."': '"Fire_Damage_Reduction"] = "Ця навичка зменшує шкоду від вогню на <color=#42f105>{0}%</color> за рівень."',
    '"Fall_Damage_Reduction"] = "This skill will reduce fall damage by <color=#42f105>{0}%</color> per level."': '"Fall_Damage_Reduction"] = "Ця навичка зменшує шкоду від падіння на <color=#42f105>{0}%</color> за рівень."',
    '"No_Cold_Damage"] = "This skill prevents you from being damaged by the cold."': '"No_Cold_Damage"] = "Ця навичка запобігає отриманню шкоди від холоду."',
    '"Wounded_Resist"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of immediately getting up after being wounded."': '"Wounded_Resist"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень миттєво піднятися після поранення."',
    '"Animal_Damage_Resist"] = "This skill reduces the damage taken by animals by <color=#42f105>{0}%</color> per level."': '"Animal_Damage_Resist"] = "Ця навичка зменшує шкоду від тварин на <color=#42f105>{0}%</color> за рівень."',
    '"Riding_Speed"] = "This skill increases the speed of your mounted horse by <color=#42f105>{0}%</color> per level."': '"Riding_Speed"] = "Ця навичка збільшує швидкість вашого коня на <color=#42f105>{0}%</color> за рівень."',
    '"Free_Bullet_Chance"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of not using a bullet while firing."': '"Free_Bullet_Chance"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень не витратити кулю при пострілі."',
    '"Primitive_Expert"] = "This skill makes primitive weapons lose no durability."': '"Primitive_Expert"] = "Ця навичка запобігає втраті міцності примітивної зброї."',
    '"Upgrade_Refund"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of receiving your building materials back when upgrading your building blocks."': '"Upgrade_Refund"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень повернути матеріали при покращенні будівельних блоків."',
    '"Craft_Speed"] = "This skill increases your crafting speed by <color=#42f105>{0}%</color> per level."': '"Craft_Speed"] = "Ця навичка збільшує швидкість крафту на <color=#42f105>{0}%</color> за рівень."',
    '"MaxRepair"] = "This skill will reset the durability of items to max when repairing them."': '"MaxRepair"] = "Ця навичка відновлює міцність предметів до максимуму при ремонті."',
    '"Free_Repairs"] = "This skill will allow you to repair your items for free."': '"Free_Repairs"] = "Ця навичка дозволяє вам ремонтувати предмети безкоштовно."',
    '"Durability"] = "This skill reduces durability loss by <color=#42f105>{0}%</color> per level."': '"Durability"] = "Ця навичка зменшує втрату міцності предметів на <color=#42f105>{0}%</color> за рівень."',
    '"Smelt_Speed"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to smelt ore when a log is burned, in addition to the normal smelt rate."': '"Smelt_Speed"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень переплавити руду під час згоряння дерева на додаток до звичайної швидкості переплавки."',
    '"Research_Refund"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of receiving your scrap back when researching."': '"Research_Refund"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень повернути металобрухт під час вивчення предметів."',
    '"Craft_Refund"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of receiving your components back when crafting."': '"Craft_Refund"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень повернути компоненти при крафті."',
    '"Craft_Duplicate"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level of duplicating an item while crafting."': '"Craft_Duplicate"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень дублювати предмет при крафті."',
    '"Extra_Scrap_Barrel"] = "This skill gives you <color=#42f105>{0}%</color> chance per level to receive extra scrap when smashing a barrel."': '"Extra_Scrap_Barrel"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень отримати додатковий металобрухт при знищенні бочки."',
    '"Barrel_Smasher"] = "This skill allows you to smash a barrel in 1 hit with any weapon."': '"Barrel_Smasher"] = "Ця навичка дозволяє розбивати бочки з 1 удару будь-якою зброєю."',
    '"Loot_Pickup"] = "This skill gives you a <color=#42f105>{0}%</color> chance per level to add the loot straight into your inventory when destroying a barrel"': '"Loot_Pickup"] = "Ця навичка дає вам <color=#42f105>{0}%</color> шансу за рівень додати лут прямо в інвентар при розбиванні бочки"',
}

for k, v in translations.items():
    content = content.replace(k, v)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)
